question_index:
    path:     /
    defaults: { _controller: "XTeamPlatformBundle:question:index" }
    methods:  GET

question_show:
    path:     /{id}/show
    defaults: { _controller: "XTeamPlatformBundle:question:show" }
    methods:  GET

question_new:
    path:     /new
    defaults: { _controller: "XTeamPlatformBundle:question:new" }
    methods:  [GET, POST]

question_edit:
    path:     /{id}/edit
    defaults: { _controller: "XTeamPlatformBundle:question:edit" }
    methods:  [GET, POST]

question_delete:
    path:     /{id}/delete
    defaults: { _controller: "XTeamPlatformBundle:question:delete" }
    methods:  DELETE
