tag_index:
    path:     /
    defaults: { _controller: "XTeamPlatformBundle:tag:index" }
    methods:  GET

tag_show:
    path:     /{id}/show
    defaults: { _controller: "XTeamPlatformBundle:tag:show" }
    methods:  GET

tag_new:
    path:     /new
    defaults: { _controller: "XTeamPlatformBundle:tag:new" }
    methods:  [GET, POST]

tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "XTeamPlatformBundle:tag:edit" }
    methods:  [GET, POST]

tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "XTeamPlatformBundle:tag:delete" }
    methods:  DELETE
