user_index:
    path:     /
    defaults: { _controller: "XTeamPlatformBundle:user:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "XTeamPlatformBundle:user:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "XTeamPlatformBundle:user:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "XTeamPlatformBundle:user:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "XTeamPlatformBundle:user:delete" }
    methods:  DELETE
