XTeam\PlatformBundle\Entity\badge:
    type: entity
    table: null
    repositoryClass: XTeam\PlatformBundle\Repository\badgeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        icon:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
