XTeam\PlatformBundle\Entity\user:
    type: entity
    table: null
    repositoryClass: XTeam\PlatformBundle\Repository\userRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        profession:
            type: string
            length: 255
            nullable: true
        business:
            type: string
            length: 255
            nullable: true
        statut:
            type: string
            length: 255
        promo:
            type: string
            length: 255
            nullable: true
        git:
            type: string
            length: 255
        twitter:
            type: string
            length: 255
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        linkedin:
            type: string
            length: 255
        avatar:
            type: string
            length: 255
    lifecycleCallbacks: {  }
